<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Project-specific properties only -->
    <RootNamespace>TextToSpeechCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PiperSharp" />
    <PackageReference Include="NAudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TranslationTools\TranslationTools.csproj" />
  </ItemGroup>
</Project>
